# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
   user.label: ""
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    if [ -z $"(user.label)" ]; then
       echo "NULL"
    else
       echo $(user.label)
    fi
  displayName: 'Run a multi-line script'
